# Generated by Django 5.0.6 on 2024-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Модель телефона')),
                ('price', models.CharField(verbose_name='Цена')),
                ('image', models.URLField(verbose_name='URL ссылка на изображение')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(default=True, verbose_name='Поддержка LTE')),
                ('slug', models.SlugField(unique=True, verbose_name='URL_slug')),
            ],
        ),
    ]
